name: Check Cards

on: [push, pull_request]

jobs:
  check-cards:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run card check script
      run: python .github/scripts/check-cards.py

    - name: Run internal link check script
      run: python .github/scripts/check-internal-links.py