name: Check Cards

on: [push, pull_request]

jobs:
  check-cards:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Run card tag check script
        run: python3 scripts/check-tag.py
      
      - name: Run card name check script
        run: python3 scripts/check-card-name.py

      - name: Run card index generation and internal link check script
        run: python3 scripts/check-internal-links.py
